# Generated by Django 4.2.30 on 2026-09-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgnode',
            name='level',
            field=models.IntegerField(choices=[(1, '区'), (2, '乡镇'), (3, '村')], default=1),
        ),
        migrations.AddIndex(
            model_name='orgnode',
            index=models.Index(fields=['level'], name='org_node_level_cb5fc6_idx'),
        ),
        migrations.AddIndex(
            model_name='orgnode',
            index=models.Index(fields=['parent_id'], name='org_node_parent__dbfc14_idx'),
        ),
    ]
