# Generated by Django 4.2.30 on 2026-09-13 02:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        ('ranger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=128)),
                ('ranger_name', models.CharField(blank=True, default='', max_length=64)),
                ('town_name', models.CharField(blank=True, default='', max_length=64)),
                ('detail', models.TextField(blank=True, default='')),
                ('level', models.CharField(default='medium', max_length=16)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'warning',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranger_name', models.CharField(blank=True, default='', max_length=64)),
                ('type', models.IntegerField(default=4)),
                ('description', models.TextField(blank=True, default='')),
                ('images', models.JSONField(blank=True, default=list)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('handler_id', models.IntegerField(blank=True, null=True)),
                ('handler_name', models.CharField(blank=True, default='', max_length=64)),
                ('handle_note', models.TextField(blank=True, default='')),
                ('handle_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ranger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='ranger.ranger')),
                ('town', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.orgnode')),
            ],
            options={
                'db_table': 'event',
            },
        ),
    ]
