# Generated by Django 4.2.30 on 2026-09-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warning',
            name='status',
            field=models.IntegerField(choices=[(0, '未处理'), (1, '已处置')], default=0),
        ),
        migrations.AddIndex(
            model_name='warning',
            index=models.Index(fields=['type'], name='warning_type_01b367_idx'),
        ),
        migrations.AddIndex(
            model_name='warning',
            index=models.Index(fields=['status'], name='warning_status_ff57cf_idx'),
        ),
        migrations.AddIndex(
            model_name='warning',
            index=models.Index(fields=['level'], name='warning_level_77d13f_idx'),
        ),
    ]
