# Generated by Django 4.2.30 on 2026-09-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_area_warning_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[(0, '待处理'), (1, '处理中'), (2, '已闭环'), (3, '已驳回')], default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.IntegerField(choices=[(1, '火情'), (2, '隐患'), (3, '破坏森林资源'), (4, '其他')], default=4),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status'], name='event_status_c263a9_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['type'], name='event_type_d26f77_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['town'], name='event_town_id_faeed6_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_at'], name='event_created_989bde_idx'),
        ),
    ]
