# Generated by Django 4.2.30 on 2026-09-13 02:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ranger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('cover_url', models.CharField(blank=True, default='', max_length=255)),
                ('type', models.IntegerField(default=1)),
                ('content_url', models.CharField(blank=True, default='', max_length=255)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('sort', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='StudyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranger_name', models.CharField(blank=True, default='', max_length=64)),
                ('course_title', models.CharField(blank=True, default='', max_length=128)),
                ('progress', models.IntegerField(default=0)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_records', to='training.course')),
                ('ranger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_records', to='ranger.ranger')),
            ],
            options={
                'db_table': 'study_record',
            },
        ),
    ]
