# Generated by Django 4.2.30 on 2026-09-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.IntegerField(choices=[(0, '下架'), (1, '上架')], default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.IntegerField(choices=[(1, '视频'), (2, '图文')], default=1),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status'], name='course_status_7f657c_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['type'], name='course_type_8168e7_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['sort'], name='course_sort_e3322b_idx'),
        ),
        migrations.AddIndex(
            model_name='studyrecord',
            index=models.Index(fields=['course'], name='study_recor_course__b433d6_idx'),
        ),
        migrations.AddIndex(
            model_name='studyrecord',
            index=models.Index(fields=['ranger'], name='study_recor_ranger__1273a1_idx'),
        ),
        migrations.AddIndex(
            model_name='studyrecord',
            index=models.Index(fields=['progress'], name='study_recor_progres_78d165_idx'),
        ),
    ]
