# Generated by Django 4.2.30 on 2026-09-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(default='city', max_length=32)),
                ('priority', models.CharField(default='p2', max_length=8)),
                ('base_url', models.CharField(blank=True, default='', max_length=255)),
                ('auth_type', models.CharField(default='none', max_length=16)),
                ('enabled', models.BooleanField(default=False)),
                ('direction', models.CharField(default='bidirectional', max_length=16)),
                ('desc', models.TextField(blank=True, default='')),
                ('endpoints', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'external_system',
            },
        ),
    ]
