# Generated by Django 4.2.30 on 2026-09-13 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('boundary', models.JSONField(blank=True, default=list)),
                ('area_size', models.FloatField(blank=True, null=True)),
                ('key_points', models.JSONField(blank=True, default=list)),
                ('ranger_name', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='org.orgnode')),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Ranger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('id_card', models.CharField(blank=True, default='', max_length=32)),
                ('avatar_url', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('online', models.BooleanField(default=False)),
                ('month_distance', models.FloatField(default=0)),
                ('month_checkin_rate', models.FloatField(default=0)),
                ('score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rangers', to='ranger.area')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rangers', to='org.orgnode')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='village_rangers', to='org.orgnode')),
            ],
            options={
                'db_table': 'ranger',
            },
        ),
        migrations.CreateModel(
            name='Patrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranger_name', models.CharField(blank=True, default='', max_length=64)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('distance', models.FloatField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('track', models.JSONField(blank=True, default=list)),
                ('key_points_hit', models.JSONField(blank=True, default=list)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ranger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrols', to='ranger.ranger')),
                ('town', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.orgnode')),
            ],
            options={
                'db_table': 'patrol',
            },
        ),
    ]
