# Generated by Django 4.2.30 on 2026-09-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranger',
            name='status',
            field=models.IntegerField(choices=[(0, '离职'), (1, '在岗')], default=1),
        ),
        migrations.AddIndex(
            model_name='ranger',
            index=models.Index(fields=['status'], name='ranger_status_387852_idx'),
        ),
        migrations.AddIndex(
            model_name='ranger',
            index=models.Index(fields=['town'], name='ranger_town_id_91a2cc_idx'),
        ),
        migrations.AddIndex(
            model_name='ranger',
            index=models.Index(fields=['online'], name='ranger_online_326655_idx'),
        ),
    ]
