# Generated by Django 4.2.30 on 2026-09-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranger', '0002_ranger_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['town'], name='area_town_id_a213f9_idx'),
        ),
    ]
