# Generated by Django 4.2.30 on 2026-09-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='role',
            field=models.CharField(choices=[('super', '超级管理员'), ('district', '区级管理员'), ('town', '乡镇管理员')], default='district', max_length=16),
        ),
        migrations.AddIndex(
            model_name='adminuser',
            index=models.Index(fields=['role'], name='admin_user_role_df2691_idx'),
        ),
        migrations.AddIndex(
            model_name='adminuser',
            index=models.Index(fields=['town'], name='admin_user_town_id_597ecd_idx'),
        ),
    ]
