# Generated by Django 4.2.30 on 2026-09-13 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        ('ranger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('patrol_weight', models.IntegerField(default=40)),
                ('event_weight', models.IntegerField(default=30)),
                ('study_weight', models.IntegerField(default=30)),
                ('patrol_target', models.FloatField(blank=True, null=True)),
                ('checkin_target', models.IntegerField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'assessment_rule',
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranger_name', models.CharField(blank=True, default='', max_length=64)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('patrol_score', models.FloatField(default=0)),
                ('event_score', models.FloatField(default=0)),
                ('study_score', models.FloatField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('rank_in_town', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ranger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='ranger.ranger')),
                ('town', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='org.orgnode')),
            ],
            options={
                'db_table': 'assessment_result',
                'unique_together': {('ranger', 'year', 'month')},
            },
        ),
    ]
