# Generated by Django 4.2.30 on 2026-09-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assessmentresult',
            index=models.Index(fields=['year', 'month'], name='assessment__year_b873a3_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentresult',
            index=models.Index(fields=['town'], name='assessment__town_id_d0875a_idx'),
        ),
    ]
